### ISSUE TITLE
Feature Request: Index all the things!

### ISSUE THREAD

**Issue by cpcodes** [SvenWerlen/moulinette-tiles#1]
First, I'd like to say that this whole suite of tools is amazing work. Thank you.

This might be another module or it might integrate nicely into this one, but while this does fantastically with tile sets, it would be great to have this search functionality for non-tile images like token art, etc., that is less structured (likely in a single folder) - basically just the random art that people pull in during the course of play.

Also, there are quite a few sets of structured assets living in the Foundry core and many game systems (D&D 5e and Pathfinder 2 both have extensive icon sets). Having these indexed and easily searchable would also be handy. This might be doable just by allowing more than a single path to be entered for the assets custom path (or having a nice UI that allows selecting folders to index).

**Comment by azhreii** [comment]
When dropping an image in as a token you can select which actor it represents. Is it possible to only direct where it looks for an actor to a specific folder(s) and a default grid/image size for dropped in tokens ?

**Comment by SvenWerlen** [comment]
@cpcodes regarding search on non-tile images, the module supports tokens, sounds and journal articles too.  I also recently implemented a way to scan assets from core, systems, and other modules. Check:
https://github.com/SvenWerlen/moulinette-core/tree/main/docs

I'm going to close this issue then. 
@azhreii : could you please create a new issue for your request since it's not related to the initial request from cpcodes. Thx!
